//! Conformance test against a real (`sqlite3`-authored, via Python's
//! stdlib `sqlite3` module) multi-page SQLite database with a Chromium
//! `History`-shaped schema: 800 `urls` rows across ~30 4096-byte pages
//! (forcing real interior/leaf b-tree descent) and one deliberately oversized
//! title (6009 bytes) forcing an overflow-page chain. Generated by
//! `artifacts/chrome_history_sample/README.md`'s script; skipped if the
//! fixture is not present (e.g. a fresh checkout before it's regenerated).

use forensic_rs::traits::db::ForensicValue;

use frnsc_sqlite::sqlite::db::SqliteDb;

const FIXTURE: &str = "artifacts/chrome_history_sample/History";

fn open_fixture() -> Option<SqliteDb> {
    match SqliteDb::open(FIXTURE) {
        Ok(db) => Some(db),
        Err(_) => {
            eprintln!("SKIP: fixture unavailable at {FIXTURE}");
            None
        }
    }
}

#[test]
fn lists_expected_tables() {
    let Some(db) = open_fixture() else { return };
    let mut tables = db.table_names();
    tables.sort();
    assert_eq!(tables, vec!["urls", "visits"]);
}

#[test]
fn reads_all_800_url_rows_in_rowid_order() {
    let Some(db) = open_fixture() else { return };
    let table = db.table("urls").unwrap();
    let mut rows = table.iter_rows().unwrap();

    let mut count = 0usize;
    let mut last_id = 0i64;
    while rows.next_row().unwrap() {
        let (rowid, values) = rows.current_row().unwrap();
        count += 1;
        // rowid-aliased `id` column must equal the cell's own rowid, and
        // rows must come back in ascending rowid order (left-to-right leaf
        // traversal).
        assert_eq!(values[0], ForensicValue::I64(*rowid));
        assert!(*rowid > last_id, "rows out of order: {rowid} after {last_id}");
        last_id = *rowid;
    }
    assert_eq!(count, 800);
    assert_eq!(last_id, 800);
}

#[test]
fn first_row_matches_known_values() {
    let Some(db) = open_fixture() else { return };
    let table = db.table("urls").unwrap();
    let mut rows = table.iter_rows().unwrap();
    assert!(rows.next_row().unwrap());
    let (rowid, values) = rows.current_row().unwrap();
    assert_eq!(*rowid, 1);
    assert_eq!(values[0], ForensicValue::I64(1));
    assert_eq!(
        values[1],
        ForensicValue::Text("https://example0.test/path/0?q=0".into())
    );
    assert_eq!(
        values[2],
        ForensicValue::Text("Example Page 0 - HbolMJUevblAbkHClEQa".into())
    );
    assert_eq!(values[3], ForensicValue::I64(0)); // visit_count
    assert_eq!(values[5], ForensicValue::I64(13350000000000000)); // last_visit_time
}

#[test]
fn overflow_row_reassembles_the_full_6009_byte_title() {
    let Some(db) = open_fixture() else { return };
    let table = db.table("urls").unwrap();
    let mut rows = table.iter_rows().unwrap();
    let mut found = false;
    while rows.next_row().unwrap() {
        let (rowid, values) = rows.current_row().unwrap();
        if *rowid == 501 {
            // row index 500 (0-based) -> rowid 501 (INTEGER PRIMARY KEY
            // starts at 1).
            let ForensicValue::Text(title) = &values[2] else {
                panic!("expected text title")
            };
            assert!(title.starts_with("OVERFLOW-"));
            assert_eq!(title.len(), 6009, "overflow-page reassembly produced the wrong length");
            found = true;
            break;
        }
    }
    assert!(found, "row 501 (the overflow row) was not reached");
}

#[test]
fn last_row_matches_known_values() {
    let Some(db) = open_fixture() else { return };
    let table = db.table("urls").unwrap();
    let mut rows = table.iter_rows().unwrap();
    let mut last = None;
    while rows.next_row().unwrap() {
        last = Some(rows.current_row().unwrap().clone());
    }
    let (rowid, values) = last.unwrap();
    assert_eq!(rowid, 800);
    assert_eq!(
        values[1],
        ForensicValue::Text("https://example799.test/path/799?q=799".into())
    );
    assert_eq!(values[3], ForensicValue::I64(22)); // 799 % 37
}

#[test]
fn visits_table_foreign_keys_line_up_with_urls() {
    let Some(db) = open_fixture() else { return };
    let table = db.table("visits").unwrap();
    let mut rows = table.iter_rows().unwrap();
    let mut count = 0usize;
    while rows.next_row().unwrap() {
        let (rowid, values) = rows.current_row().unwrap();
        assert_eq!(values[0], ForensicValue::I64(*rowid)); // id rowid alias
        let ForensicValue::I64(url_id) = values[1] else {
            panic!("expected integer url id")
        };
        assert!((1..=800).contains(&url_id));
        count += 1;
    }
    assert_eq!(count, 800);
}

#[test]
fn generic_forensic_db_bridge_round_trips() {
    use forensic_rs::traits::db::ForensicDb;
    let Some(db) = open_fixture() else { return };
    let dyn_db: &dyn ForensicDb = &db;
    let mut tables = dyn_db.list_tables().unwrap();
    tables.sort();
    assert_eq!(tables, vec!["urls", "visits"]);

    let table = dyn_db.table("urls").unwrap();
    assert_eq!(table.columns().len(), 7);
    let mut rows = table.iter_rows().unwrap();
    assert!(rows.next().unwrap());
    assert_eq!(rows.read(0).unwrap(), ForensicValue::I64(1));
    assert_eq!(
        rows.read_named("url").unwrap(),
        ForensicValue::Text("https://example0.test/path/0?q=0".into())
    );
}
